### PR TITLE
refactor Audio

### PR DESCRIPTION
**Pull request by nkast**

### CODE REVIEW

**Comment by damian-666** [comment]
hi  looks great, doe this mean i might be able to apply physics driven reverb based on room size and such?   no way am i going to use XNA studio.      ill cast some rays ...  a question, ?  will KNI work with existing code, simple pixel shader on webassembly android linux windows?  iss it in a working state  for bssic 2d, if i pull and buiid and what is the target ETA for stable release? , im trying to figure a way to put it in Avalonia.. can hook it to my 2d pyhsics fork and or bepu3.. with docking scripting  for an IDE.. so much flux i cant decide..

**Comment by nkast** [comment]
Those changes were necessary to decouple the various implementations from the framework. See #1176.
Anything under the Xna.Platform namespace is for internal use.
There is nothing new here, the reverb types were used by the Xact engine.

Because of the heavy refactoring a couple of bugs might slip in, but as soon as they are spotted they are fixed before the next release. Meanwhile, every release had bug fixes and improvements over the legacy code.
Existing .fx shaders will work, perhaps better [than they were before](http://blog.nkast.gr/post/what-s-new-in-kni-v3-10).

I haven't tried to embed KNI in Avalonia. @AristurtleDev has already done it for MonoGame. I guess porting the project to KNI shouldn't be that hard. https://github.com/AristurtleDev/MonoGame.Avalonia/tree/main

**Comment by nkast** [comment]
Now that #1176 is done, I'll try to separate .xact from Framework.Audio.dll.

The Xact code is halfway reversed engineered, there is no documentation for the format, and the authoring tool is deprecated.
I don't think that anyone would like contribute into the implementation or to use it for future projects.

Meanwhile we might want to start working on a new extension to support some common features on an open and well defined format.
events, cues, wavebands, dsp/effects, etc

**Comment by damian-666** [comment]
Thanks for getting back back to me.

its ok, looks look ill try this , 


_i dont have time to make this concise but wanted to share my use case want what i tried before when we last talked abut gutting out the XACT and calling effects via apis._

like this case

https://stackoverflow.com/questions/16289951/xna-monogame-is-there-an-alternative-to-xact   answer is NO.   unless you fix it..   you can link in there..   i did find a reverb engine that did i work , if this doesn't go well ill dig it up.     there are DSP ones mabye..  FPGA , etc..  lots of changes .


_the suggestion i have is in italic_

and il try this. 
  **embed KNI in Avalonia.**   i have 2 others with tabbing.. all are not optimal they use writeable bitmap, but ok for design.  So if IDE works on linux, pc, its good enough , even if performance not  optimal.     i didn't choose in game level design feature  for UI.  so i dont deploy all that.. 

 
I make my own sound bank, cues,  ambient sound tools and  and all that . 
   i can share it if you are curious.
   
    its pretty high level so just unifying effects Filters and Reverb, with one code base with minimal effort and first strip out  the XACT sfuff would be great.   
    
   i see this but I don't use the content pipeline at all for sounds, i would want direct access to the sound effect params and make my own tooling and save my own data formats.
   
    https://github.com/absoluteAquarian/MonoSound/wiki/SoundEffect-Loading
   
if just Effects could be applied at real-time that would be great.  the cues,  and sound banks i would think are too high level, tooling level.

i would start with" stone cave"  the presets from Silk,   try put it on a soundEffect 

In my use case, all cues are from the physics engine, and i would not need any mixing features or separate tools.
id drag drop a wav file ,  like gunshotak44,wav  to a physics object. put an emitter on there.




   to some object , then go to a reverb effects  list and apply that to the l emitter, or even to the listener  ( but thats for continuous filtering, another feature i would hope that id be free to implement with an nice thin open framework) 
   
  then at real time adjust room size based on measurement of the room my 2d listener and or emitter is in.   
  
  
  something to consider is https://fna-xna.github.io/    Faudio.   but i don't know that it works on all the platforms that are important for indies wanting reach and find their audience with original game art and concept. 
  
  if Effects and Filters,  worked on all windows dx, linux,  droid,  webassembly   ..  would be great..   and soon windows on ARM will be like the mac M  chips.  wiht FPGAs for the DSPs. and filters, and AI low power . something to consider.  the middleward should do that  though.

this might help
https://github.com/opentk/opentk/tree/f3539ad1fda98af9b265e941e0aecfb4662a9bbe/src/OpenAL/OpenTK.OpenAL.Extensions

https://github.com/absoluteAquarian/MonoSound/wiki/SoundEffect-Loading    i don't like he uses content and special files.   something  in there might help.. FMOD is way overkill.  

https://github.com/kcat/openal-soft/issues/550    this means there might be a way in wbeassembly

Like Stride i don't deploy my IDE stuff, that will be is Avalonia based.   Avalonia is build over skiaSharp that has crossover , and makes it hard for me to decide what to do.   Stride level editor  is  porting to Avalonia btw.  but they have a weird shader format and too bloated.

>>>>>

 but this is where i left off when i tried to modify monogame to let me apply a set  of reverb params like the ones you can audition in the old XACT tool.  I don't use teh content pipeline for audio i use load a sound effect from a wave file in the dll.    most are short sounds , guns and lasers and are cycled or attached to collisions in physics, ( my cues) 

so i tried but failed,, and suggest naively 

_1, like you said strip out all XACT. parsing code.  refactor,

2. make the reverb structs public with comments, take some of the samples of  auditioning pre presets for sets of values for reverbs. They're all in the **Silk codebase 

  things like big Stone cave , etc.   concertHall..


3. Try to apply on presets to a soundeffect,   make an instance and play it in your own code to see if it works. I don't think every sound effect instance can necessarily have its own reverb settings. And if it's the case, it's fine.  i call the Update gets called it had a slot in the driver **but i think since i never parses a XACT file, that something was not initialized.**  I was using Avalonia as a test rig and GL ,  not everything was implennted,, instead  i would  first use WindowsDX , i never tried that...

4. if any reverb works put the silk presets ( look like the XNA studio ones)  as static structs so that people can have a starting point and easily discover them.. I would hope to be able to bind a list box and live audition them while the sound is playing.   I don't know that they need to wrap a value array or jsut be normal properties.   ( see Silk  presets serach Reverb)

5. If DirectX has reverb working  on windows, i would try then GL, then here's param value mapping  hand rolled code that's really valuable in monogame, where it maps from XAudio to SDL, or if you're an open GL platform, the parameters for sound for reverbs don't sound the same or mean the same. adjustment map the canonized XACT version to  to the other. Then I would document What the physical meanings are of those in the XAML on the On the DSP parameter structure. fields._ 


people say the audio sucks in monogame but that's up to the middleware.    the other libraries are overbladed. And dont use DSP.     on suggested use openAL everywhere, other to just use FAudio, others say its good enough,

separating audio from monogame itself is a possible option.    

 IM not sure the content  pipe adds value.  I load wav files from a shared dll.  I wont use a separate sound design tool even the chat bot can make features like that in my main IDE . ( or used to) , mixers and sliders and folder watchers), and i put a little grip on my objects as a sound emitter. 

 i would probably  then at real time adjust the say room size if my emitter and or listener gets in a bigger ro , id measure it with ray casts or something and make a guess.  its physics based sound, i let the game physics  do the sound design.
 
for documentation i would hope for, 
Parameters like room size is that i meters and. you know, wet, dry mix, whether it's in decibels, what's the max of value and what's the min value. And if it exceeds, I would just clamp rather than throw exceptions.

ill try  to see if i can test and   get some IDE with 2d physics in it.. with docking..  and or bepu2. problem is skia also have rendering and bepu2 moved to another transpiler and openTK    for my 3d project.
    
    
for an indie game dev :     Windows, (DX, GL, or Vulcan, soon ARM) , Linux, Mac,  android   and Webassmbly give all the reach.     nothing else is worth the hoops.   iOs, i proably woild do last.  also for scientific visualization i need the webassembly and the Ai and the linux and tooling on linux.

**Pull request merged**
